apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: shopping-cart-scala

resources:
  - inventory.yaml
  - shopping-cart.yaml
  - common/rbac.yaml
  - common/kafka.yaml