apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: shopping-cart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart

  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: "shopping-cart:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
        - name: APPLICATION_SECRET
          value: ZPFv7e27x7dZalf9SNR7uXbCmUaghqzh
        - name: POSTGRESQL_URL
          value: "jdbc:postgresql://postgresql/shopping_cart"
        - name: POSTGRESQL_USERNAME
          value: shopping_cart
        - name: POSTGRESQL_PASSWORD
          value: shopping_cart
        - name: KAFKA_SERVICE_NAME
          value: "_clients._tcp.strimzi-kafka-brokers"
        - name: REQUIRED_CONTACT_POINT_NR
          value: "3"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 0.25
            memory: 512Mi
        ports:
          - name: management
            containerPort: 8558
          - name: services
            containerPort: 9008
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
  - name: services
    port: 9008
    targetPort: 9008
  selector:
    app: shopping-cart
  type: LoadBalancer